Repository modelcontextprotocol/inspector, pull requests merged in 2025-04, with the labels that each got.

#234 fix: prop.type not accept integer
  client/src/components/ToolsTab.tsx
Labels: bug, waiting on submitter

#244 feat: add new toast and add copy button to JSON.
  client/package.json
  client/src/App.tsx
  client/src/components/History.tsx
  client/src/components/JsonView.tsx
  client/src/components/PromptsTab.tsx
  client/src/components/ResourcesTab.tsx
  client/src/components/SamplingTab.tsx
  client/src/components/ToolsTab.tsx
  client/src/components/ui/select.tsx
  client/src/components/ui/toast.tsx
  client/src/components/ui/toaster.tsx
  client/src/hooks/use-toast.ts
  client/src/index.css
  client/src/lib/hooks/useConnection.ts
  client/src/main.tsx
  package-lock.json
Labels: enhancement, waiting on submitter

#243 Add MCP proxy address config support, better error messages, redesigned Config panel
  README.md
  client/package.json
  client/src/App.tsx
  client/src/components/Sidebar.tsx
  client/src/components/__tests__/Sidebar.test.tsx
  client/src/components/ui/tooltip.tsx
  client/src/lib/configurationTypes.ts
  client/src/lib/constants.ts
  client/src/lib/hooks/useConnection.ts
  client/src/main.tsx
  client/src/utils/configUtils.ts
  package-lock.json
  server/src/index.ts
Labels: enhancement, waiting on submitter

#271 feat: Progress Support for Long Running Tool Calls ⏳
  README.md
  client/src/App.tsx
  client/src/components/Sidebar.tsx
  client/src/components/ToolsTab.tsx
  client/src/components/__tests__/Sidebar.test.tsx
  client/src/components/__tests__/ToolsTab.test.tsx
  client/src/lib/configurationTypes.ts
  client/src/lib/constants.ts
  client/src/lib/hooks/__tests__/useConnection.test.tsx
  client/src/lib/hooks/useConnection.ts
  client/src/utils/configUtils.ts
Labels: enhancement, waiting on submitter

#264 refactor(json): Consolidate JSON utilities and type definitions
  client/src/components/DynamicJsonForm.tsx
  client/src/components/JsonView.tsx
  client/src/components/ToolsTab.tsx
  client/src/components/__tests__/DynamicJsonForm.test.tsx
  client/src/utils/__tests__/jsonUtils.test.ts
  client/src/utils/__tests__/schemaUtils.test.ts
  client/src/utils/jsonUtils.ts
  client/src/utils/schemaUtils.ts
Labels: waiting on submitter

#290 Fix Reconnect handler
  client/src/components/Sidebar.tsx
Labels: bug

#274 fix dark mode color and padding for the tab item
  client/src/components/ListPane.tsx
  client/src/components/PromptsTab.tsx
  client/src/components/ResourcesTab.tsx
  client/src/components/Sidebar.tsx
  client/src/components/ToolsTab.tsx
Labels: waiting on submitter

#286 feat: 🎸 Add clear button for error notifications
  client/src/App.tsx
  client/src/components/Sidebar.tsx
  client/src/components/__tests__/Sidebar.test.tsx
Labels: enhancement, waiting on submitter

#272 Enable Authentication header name configuration
  README.md
  client/src/App.tsx
  client/src/components/Sidebar.tsx
  client/src/components/__tests__/Sidebar.test.tsx
  client/src/lib/hooks/useConnection.ts
Labels: enhancement, waiting on submitter

#270 feat: Show initialize request/response in History panel (#269)
  client/src/lib/hooks/__tests__/useConnection.test.tsx
  client/src/lib/hooks/useConnection.ts
Labels: enhancement, waiting on submitter

#320 fix: console warning in sidebar
  client/src/components/Sidebar.tsx
Labels: bug

#284 fix: When tool type cannot be determined, use DynamicJsonForm
  client/src/components/DynamicJsonForm.tsx
  client/src/components/ToolsTab.tsx
  client/src/components/__tests__/DynamicJsonForm.test.tsx
Labels: enhancement, waiting on submitter

#279 feat: QoL improvements for OAuth Callback
  client/src/App.tsx
  client/src/components/OAuthCallback.tsx
  client/src/utils/__tests__/oauthUtils.ts
  client/src/utils/oauthUtils.ts
Labels: enhancement, waiting on submitter

#280 fix: Disconnecting should clear oauth state
  client/src/lib/auth.ts
  client/src/lib/hooks/useConnection.ts
Labels: bug, waiting on submitter

#318 Update README requirement node js version
  README.md
Labels: documentation, waiting on submitter

#294 add support for Streamable HTTP server
  client/src/App.tsx
  client/src/components/Sidebar.tsx
  client/src/lib/hooks/useConnection.ts
  server/src/index.ts
Labels: enhancement
