Repository modelcontextprotocol/inspector, pull requests merged in 2025-07, with the labels that each got.

#473 chore: Add node-version to package.json and workflows
  .github/workflows/e2e_tests.yml
  .github/workflows/main.yml
  .node-version
  package.json
Labels: waiting on submitter

#567 feat: add "Copy JSON" button
  client/src/components/DynamicJsonForm.tsx
  client/src/components/__tests__/DynamicJsonForm.test.tsx
Labels: waiting on submitter

#564 feat: Add resource_link content type support to ToolResults component
  client/src/App.tsx
  client/src/components/ResourceLinkView.tsx
  client/src/components/ToolResults.tsx
  client/src/components/ToolsTab.tsx
  client/src/components/__tests__/ToolsTab.test.tsx
Labels: waiting on submitter

#517 make auth token configurable via env var
  README.md
  client/bin/start.js
  server/src/index.ts
Labels: waiting on submitter

#597 Missing mandatory parameter in the Inspector's CLI command
  README.md
Labels: documentation

#345 feat: support manual entry of OAuth client information
  client/src/App.tsx
  client/src/components/Sidebar.tsx
  client/src/components/__tests__/Sidebar.test.tsx
  client/src/lib/auth.ts
  client/src/lib/constants.ts
  client/src/lib/hooks/__tests__/useConnection.test.tsx
  client/src/lib/hooks/useConnection.ts
Labels: enhancement, waiting on submitter, waiting on sdk

#535 add: elicitation support
  client/package.json
  client/src/App.tsx
  client/src/components/DynamicJsonForm.tsx
  client/src/components/ElicitationRequest.tsx
  client/src/components/ElicitationTab.tsx
  client/src/components/__tests__/DynamicJsonForm.test.tsx
  client/src/components/__tests__/ElicitationRequest.test.tsx
  client/src/components/__tests__/ElicitationTab.test.tsx
  client/src/lib/hooks/__tests__/useConnection.test.tsx
  client/src/lib/hooks/useConnection.ts
  client/src/utils/__tests__/jsonUtils.test.ts
  client/src/utils/jsonUtils.ts
  package-lock.json
  package.json
Labels: waiting on submitter
